sudo = false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
  - pip install cython
  - pip install -r requirements
install:
  - python setup.py develop
script:
  - coverage run -m haas
after_success:
  - coveralls
