language: python
matrix:
  include:
    - python: "2.6"
      env: REQUIREMENTS=test-requirements.txt
    - python: "2.7"
      env: REQUIREMENTS=test-requirements.txt
    - python: "3.3"
      env: REQUIREMENTS=test-requirements.txt
    - python: "3.4"
      env: REQUIREMENTS=test-requirements.txt
before_install:
  - pip install cython
  - pip install codecov
  - pip install -r $REQUIREMENTS
install:
  - python setup.py develop
script:
  - coverage run -m haas
after_success:
  - codecov
