language: python
sudo: false

branches:
  only:
    master

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
    - ccache

cache:
  pip: true
  directories:
    - $HOME/.ccache

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip wheel
  - pip install --upgrade -r requirements.txt
  - pip install -r test-requirements.txt
install:
  - pip install -e .
  - alias run-tests="coverage run -p -m haas trait_documenter"
script:
  - pip install sphinx==1.2.*
  - run-tests
  - pip install sphinx==1.3.*
  - run-tests
  - pip install sphinx==1.4.*
  - run-tests
  - pip install sphinx==1.5.*
  - run-tests
  - pip install sphinx==1.6.*
  - run-tests
  - pip install --upgrade sphinx
  - run-tests
after_success:
  - coverage combine
  - pip install codecov
  - codecov
