language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - SPHINX="sphinx==1.2.3"
  - SPHINX="sphinx"
before_install:
  - pip install traits
  - pip install $SPHINX
  - pip install codecov
  - pip install -r test-requirements.txt
install:
  - python setup.py develop
script:
  - coverage run -m haas
after_success:
  - codecov
