language: python
sudo: false

branches:
  only:
    master

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - SPHINX="sphinx==1.5.*"
  - SPHINX="sphinx==1.4.*"
  - SPHINX="sphinx==1.3.*"
  - SPHINX="sphinx==1.2.*"
  - SPHINX="sphinx"

addons:
  apt:
    packages:
    - ccache

cache:
  pip: true
  directories:
    - $HOME/.ccache

before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - pip install $SPHINX codecov
  - pip install -r test-requirements.txt
install:
  - pip install -e .
script:
  - coverage run -m haas
after_success:
  - codecov
